# Generated by Django 6.0.4 on 2026-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("issuer", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("credential_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="certificates/")),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=150)),
                ("degree", models.CharField(max_length=150)),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                (
                    "institution_logo",
                    models.ImageField(blank=True, upload_to="education/"),
                ),
                ("institution_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=300
                    ),
                ),
                ("company_logo", models.ImageField(blank=True, upload_to="companies/")),
                ("company_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Experience",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("profile_image", models.ImageField(blank=True, upload_to="profile/")),
                ("resume", models.FileField(blank=True, upload_to="resume/")),
            ],
            options={
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(help_text="Comma-separated", max_length=300),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework"),
                            ("database", "Database"),
                            ("tool", "Tool"),
                            ("cloud", "Cloud"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(default=80, help_text="1-100"),
                ),
                ("icon_class", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("dribbble", "Dribbble"),
                            ("behance", "Behance"),
                            ("medium", "Medium"),
                            ("dev", "Dev.to"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, help_text="Font Awesome class", max_length=50
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
