# Generated by Django 6.0.4 on 2026-05-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome class for category icon (e.g., 'fas fa-code')", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='custom_icon',
            field=models.ImageField(blank=True, help_text='Upload custom icon (SVG/PNG). Only used if Font Awesome is disabled', upload_to='skill_icons/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.URLField(blank=True, help_text='Link to homepage, documentation, or GitHub repo'),
        ),
        migrations.AddField(
            model_name='skill',
            name='use_font_awesome',
            field=models.BooleanField(default=True, help_text='Use Font Awesome icon? If unchecked, upload custom SVG/PNG'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fab fa-python'). Only used if Font Awesome is enabled", max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory'),
        ),
    ]
