# Generated by Django 6.0.4 on 2026-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skillcategory_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this skill from the website'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this entire category from the website'),
        ),
    ]
