# Generated by Django 6.0.4 on 2026-05-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skill_is_active_skillcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='custom_icon',
            field=models.FileField(blank=True, help_text='Upload custom icon (SVG/PNG/JPG). Only used if Font Awesome is disabled', upload_to='skill_icons/'),
        ),
    ]
