# Generated by Django 6.0.4 on 2026-05-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skill_custom_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='glow_color',
            field=models.CharField(default='#ec4899', help_text='Hex color for hover glow effect (e.g., #ec4899)', max_length=7),
        ),
    ]
