# Generated by Django 6.0.4 on 2026-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill_glow_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='custom_icon',
            field=models.FileField(blank=True, help_text='Upload custom SVG/PNG icon as backup', upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this social link from the website'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fab fa-github')", max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(help_text="Platform name (e.g., 'GitHub', 'Twitter')", max_length=50),
        ),
    ]
