# Generated by Django 6.0.4 on 2026-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sociallink_custom_icon_sociallink_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='use_font_awesome',
            field=models.BooleanField(default=True, help_text='Use Font Awesome icon? If unchecked, upload custom SVG/PNG'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='custom_icon',
            field=models.FileField(blank=True, help_text='Upload custom SVG/PNG icon. Only used if Font Awesome is disabled', upload_to='social_icons/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class (e.g., 'fab fa-github'). Only used if Font Awesome is enabled", max_length=50),
        ),
    ]
