# Generated by Django 6.0.4 on 2026-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sociallink_use_font_awesome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='technologies',
        ),
        migrations.AddField(
            model_name='experience',
            name='custom_technologies',
            field=models.CharField(blank=True, help_text="Comma-separated custom technologies/skills not in the skills list (e.g., 'Customer Service, Agile, Scrum')", max_length=500),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this experience from the website'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide location from the website'),
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select skills used in this role (shows with icons and links)', related_name='experiences', to='core.skill'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text="Check if this is your current position (hides end date, shows 'Present')"),
        ),
    ]
