# Generated by Django 6.0.4 on 2026-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_experience_technologies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-is_current', '-start_date'], 'verbose_name_plural': 'Experience'},
        ),
        migrations.AddField(
            model_name='experience',
            name='work_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('fully_remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('partially_remote', 'Partially Remote'), ('semi_remote', 'Semi Remote'), ('in_person', 'In Person'), ('on_site', 'On Site')], default='remote', help_text='Type of work arrangement', max_length=20),
        ),
    ]
