# Generated by Django 6.0.4 on 2026-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_experience_options_experience_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text="Check if this is your current position (hides end date field, shows 'Present' on website)"),
        ),
    ]
