# Generated by Django 6.0.4 on 2026-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_experience_work_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_visible',
        ),
        migrations.AddField(
            model_name='experience',
            name='work_type',
            field=models.CharField(choices=[('semi_remote', 'Semi-Remote'), ('remote', 'Remote'), ('in_person', 'In-Person')], default='remote', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_type_visible',
            field=models.BooleanField(default=True, help_text='Uncheck to hide work type from the website'),
        ),
    ]
