# Generated by Django 6.0.4 on 2026-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_experience_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-is_current', '-start_date'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AddField(
            model_name='education',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this education from the website'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, help_text="Degree name (e.g., 'Bachelor of Science', 'Diploma')", max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes, coursework, achievements, etc.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, help_text="Major/Field (e.g., 'Computer Science')", max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(blank=True, help_text='GPA or other metrics', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, help_text='School/University name (optional - leave blank to stay ambiguous)', max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, help_text="Check if currently studying (hides end date field, shows 'Present' on website)"),
        ),
    ]
