# Generated by Django 6.0.4 on 2026-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_education_options_education_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='custom_technologies',
            field=models.CharField(blank=True, help_text='Comma-separated custom technologies not in the skills list', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this project from the website'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select skills used in this project (shows with icons and links)', related_name='projects', to='core.skill'),
        ),
    ]
