# Generated by Django 6.0.4 on 2026-05-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section_order',
            field=models.JSONField(blank=True, default=list, help_text='Section order and visibility configuration (managed via drag-and-drop)'),
        ),
    ]
