# Generated by Django 6.0.4 on 2026-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_calendly_cta',
            field=models.BooleanField(default=True, help_text="Show the 'Schedule a meeting' card in the hero section"),
        ),
    ]
