# Generated by Django 6.0.4 on 2026-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_show_calendly_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_normal_theme',
            field=models.BooleanField(default=False, help_text="Show 'Normal' mode in the theme toggle (in addition to Dark and Light)"),
        ),
    ]
