# Generated by Django 6.0.4 on 2026-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_theme_picker',
            field=models.BooleanField(default=False, help_text='Show theme picker modal on first visit. If disabled, defaults to Light mode.'),
        ),
    ]
